import { readFile } from 'fs/promises'
import path from 'path'
import type {
  AIResult,
  AIService,
  DataSchema,
  FailureSummary,
  VisualAssertionInput,
} from './types.js'

type ClaudeResponse = {
  content?: Array<{ type: string; text?: string }>
  usage?: { input_tokens?: number; output_tokens?: number }
}

type ClaudeOptions = {
  model?: string
  baseUrl?: string
}

const DEFAULT_MODEL = 'claude-3-5-sonnet-latest'

function estimateCost(tokens: number): number {
  return Number((tokens * 0.000003).toFixed(6))
}

function makeResult<T>(value: T, reasoning: string, confidence = 0.75, tokens = 0): AIResult<T> {
  return {
    value,
    confidence,
    reasoning,
    tokensUsed: tokens,
    costUSD: estimateCost(tokens),
  }
}

async function loadSkill(name: 'generate' | 'heal' | 'plan' | 'codegen'): Promise<string> {
  const skillPath = path.resolve(process.cwd(), 'ai/skills', `${name}.md`)
  return readFile(skillPath, 'utf8')
}

async function askClaude(apiKey: string, model: string, system: string, prompt: string, baseUrl: string): Promise<AIResult<string>> {
  const response = await fetch(`${baseUrl}/messages`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system,
      messages: [{ role: 'user', content: prompt }],
    }),
  })

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`Claude API error: ${response.status} ${text}`)
  }

  const json = (await response.json()) as ClaudeResponse
  const text = json.content?.find((item) => item.type === 'text')?.text?.trim() ?? ''
  const tokens = (json.usage?.input_tokens ?? 0) + (json.usage?.output_tokens ?? 0)

  return makeResult(text, 'Generated by Claude', 0.8, tokens)
}

const env = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process?.env ?? {}

export function createClaudeAIService(apiKey: string, options: ClaudeOptions = {}): AIService {
  const enabled = env.AI_ENABLED === 'true' && apiKey.length > 0
  const model = options.model ?? DEFAULT_MODEL
  const baseUrl = options.baseUrl ?? 'https://api.anthropic.com/v1'

  const fallbackLocator = async (hint: string) => makeResult(`[data-testid="${hint.toLowerCase().replace(/\s+/g, '-')}"]`, 'Deterministic fallback selector', 0.55)

  return {
    generateLocator: async (hint, dom) => {
      if (!enabled) {
        return fallbackLocator(hint)
      }

      const skill = await loadSkill('generate')
      const result = await askClaude(apiKey, model, skill, `Hint: ${hint}\n\nDOM:\n${dom}`, baseUrl)
      return makeResult(result.value.split('\n')[0].trim(), result.reasoning, result.confidence, result.tokensUsed)
    },

    healLocator: async (broken, dom) => {
      if (!enabled) {
        return makeResult(broken, 'AI disabled, keeping existing selector as fallback', 0.4)
      }

      const skill = await loadSkill('heal')
      const result = await askClaude(apiKey, model, skill, `Broken selector: ${broken}\n\nDOM:\n${dom}`, baseUrl)
      return makeResult(result.value.split('\n')[0].trim(), result.reasoning, result.confidence, result.tokensUsed)
    },

    generateTestData: async (schema: DataSchema) => {
      if (!enabled) {
        const fallback = Object.fromEntries(schema.requiredFields.map((field) => [field, `${schema.persona}-${field}`]))
        return makeResult(fallback, 'AI disabled, generated deterministic placeholder data', 0.6)
      }

      const skill = await loadSkill('plan')
      const result = await askClaude(
        apiKey,
        model,
        skill,
        `Generate JSON test data for persona '${schema.persona}' with fields ${schema.requiredFields.join(', ')} and constraints ${JSON.stringify(schema.constraints ?? {})}.`,
        baseUrl,
      )

      try {
        return makeResult(JSON.parse(result.value) as Record<string, unknown>, result.reasoning, result.confidence, result.tokensUsed)
      } catch {
        const fallback = Object.fromEntries(schema.requiredFields.map((field) => [field, `${schema.persona}-${field}`]))
        const parsed = makeResult(fallback, 'AI returned invalid JSON; fallback used', 0.5)
        return { ...parsed, fallback }
      }
    },

    analyzeFailure: async (error, screenshotBase64) => {
      if (!enabled) {
        const summary: FailureSummary = {
          category: 'unknown',
          probableCause: error,
          nextActions: ['Review trace and screenshot'],
        }
        return makeResult(summary, 'AI disabled, raw error surfaced', 0.5)
      }

      const result = await askClaude(
        apiKey,
        model,
        'Analyze Playwright failure and return compact JSON with category, probableCause, nextActions[]',
        `Error: ${error}\nScreenshot(base64-prefix): ${screenshotBase64?.slice(0, 120) ?? 'none'}`,
        baseUrl,
      )

      try {
        return makeResult(JSON.parse(result.value) as FailureSummary, result.reasoning, result.confidence, result.tokensUsed)
      } catch {
        const summary: FailureSummary = {
          category: 'unknown',
          probableCause: result.value,
          nextActions: ['Review logs manually'],
        }
        return makeResult(summary, 'AI returned non-JSON failure summary', 0.55)
      }
    },

    assessVisualMatch: async (input: VisualAssertionInput) => {
      if (!enabled) {
        const passed = input.actualDescription.includes(input.expectedDescription)
        return makeResult(passed, 'AI disabled, simple semantic inclusion check used', 0.5)
      }

      const result = await askClaude(
        apiKey,
        model,
        'Return ONLY true or false based on semantic visual match between expected and actual descriptions.',
        `Expected: ${input.expectedDescription}\nActual: ${input.actualDescription}`,
        baseUrl,
      )

      return {
        ...makeResult(result.value.toLowerCase().includes('true'), result.reasoning, result.confidence, result.tokensUsed),
      }
    },

    planScenario: async (goal, context) => {
      if (!enabled) {
        return makeResult([`Open app`, `Execute goal: ${goal}`, 'Validate expected outcome'], 'AI disabled, deterministic plan template used', 0.55)
      }

      const skill = await loadSkill('plan')
      const result = await askClaude(apiKey, model, skill, `Goal: ${goal}\nContext: ${context}\nReturn one step per line.`, baseUrl)
      return {
        ...makeResult(result.value.split('\n').map((line) => line.trim()).filter(Boolean), result.reasoning, result.confidence, result.tokensUsed),
      }
    },

    generateCode: async (prompt, context) => {
      if (!enabled) {
        return makeResult('// AI disabled: code generation skipped', 'AI disabled', 0.4)
      }

      const skill = await loadSkill('codegen')
      return askClaude(apiKey, model, skill, `Prompt:\n${prompt}\n\nContext:\n${context}`, baseUrl)
    },
  }
}
